### ISSUE TITLE
Use "s: positive review" to get PRs ready for merge

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/sage-release-management#3]
https://github.com/sagemath/sage-release-management/blob/a246c8667ee8ee2f5723476d18d0ff82b5fd153a/git_sage/github/sage_pr.py#L16-L25 should instead check for the label ["s: positive review"](https://github.com/sagemath/sage/pulls?q=is%3Apr+is%3Aopen+label%3A%22s%3A+positive+review%22)

**Comment by vbraun** [comment]
yes, fixed
