### ISSUE TITLE
Squash by default

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/sage-release-management#4]
The recent batch of PR merges resulted in a quite messy git history with a lot of minor cleanups commits. I think PRs should be squashed instead of merged by default.

**Comment by roed314** [comment]
What did we do on trac?  I thought we used merge commits there.

**Comment by saraedum** [comment]
It also seems to me that we used merge commits from looking at the history.

My personal preference would be to keep using merge commits without squashing. There are good reasons to squash and not to squash and all projects have this discussion from time to time. I think we should just keep it the way it has been so far.

**Comment by vbraun** [comment]
Some people made boo-boos in the merge history by pushing to develop without going through me, but presumably this is over now and we can go back to the regular scheduled program. So from now on the history should be beautiful again ;)
